// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-mNFKWbeFGrfoxrEAGeboaDs80IyiRx4',
    appId: '1:837669727720:web:fd4135b66eae3643a3085d',
    messagingSenderId: '837669727720',
    projectId: 'healthcare-system-ku-5a689',
    authDomain: 'healthcare-system-ku-5a689.firebaseapp.com',
    storageBucket: 'healthcare-system-ku-5a689.firebasestorage.app',
    measurementId: 'G-Y2DMYQW3HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1EGdPZmtJa-MNeHzniiIEK3SR1JmxG44',
    appId: '1:837669727720:android:150801b4b42bb8a5a3085d',
    messagingSenderId: '837669727720',
    projectId: 'healthcare-system-ku-5a689',
    storageBucket: 'healthcare-system-ku-5a689.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTa86PVFXUXgmktgS9JLnHqADgd3ablvM',
    appId: '1:837669727720:ios:fd97f73459b3e2cca3085d',
    messagingSenderId: '837669727720',
    projectId: 'healthcare-system-ku-5a689',
    storageBucket: 'healthcare-system-ku-5a689.firebasestorage.app',
    iosBundleId: 'com.example.healthcareSystemKu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTa86PVFXUXgmktgS9JLnHqADgd3ablvM',
    appId: '1:837669727720:ios:fd97f73459b3e2cca3085d',
    messagingSenderId: '837669727720',
    projectId: 'healthcare-system-ku-5a689',
    storageBucket: 'healthcare-system-ku-5a689.firebasestorage.app',
    iosBundleId: 'com.example.healthcareSystemKu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-mNFKWbeFGrfoxrEAGeboaDs80IyiRx4',
    appId: '1:837669727720:web:980440c96698b7e5a3085d',
    messagingSenderId: '837669727720',
    projectId: 'healthcare-system-ku-5a689',
    authDomain: 'healthcare-system-ku-5a689.firebaseapp.com',
    storageBucket: 'healthcare-system-ku-5a689.firebasestorage.app',
    measurementId: 'G-2K56W6V4Q8',
  );
}
